CREATE TABLE IF NOT EXISTS LOCALIDADES (
  IDLOCALIDAD INTEGER PRIMARY KEY,
  NOMBRE TEXT NOT NULL UNIQUE,
  IDDEPARTAMENTO INTEGER NOT NULL,
  FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTOS(IDDEPARTAMENTO)
);
