CREATE TABLE IF NOT EXISTS ITRS (
  IDITR INTEGER PRIMARY KEY,
  ACTIVO TEXT NOT NULL CHECK (length(ACTIVO) = 1),
  NOMBRE TEXT NOT NULL UNIQUE,
  IDDEPARTAMENTO INTEGER NOT NULL,
  FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTOS(IDDEPARTAMENTO)
);
