CREATE TABLE IF NOT EXISTS ROLES (
  IDROL INTEGER PRIMARY KEY,
  DESCRIPCION TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TUTORES (
  IDUSUARIO INTEGER PRIMARY KEY,
  IDAREA INTEGER NOT NULL,
  IDROL INTEGER NOT NULL,
  FOREIGN KEY (IDAREA) REFERENCES AREAS(IDAREA),
  FOREIGN KEY (IDROL) REFERENCES ROLES(IDROL),
  FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO)
);
